# Generated by Django 5.2.2 on 2025-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Meal')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description of Meal')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price of Meal')),
                ('Available', models.BooleanField(default=True, verbose_name='Is Meal Available?')),
            ],
        ),
    ]
