# Generated by Django 5.2.2 on 2025-06-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='Available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='Price',
            new_name='price',
        ),
    ]
