# Generated by Django 5.2.2 on 2025-06-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_available_meal_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock of Meal'),
        ),
    ]
