# Generated by Django 5.2.2 on 2025-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_meal_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, default='meal_images/default_meal.jpg', null=True, upload_to='meal_images', verbose_name='Image of Meal'),
        ),
    ]
